# Updated : 2025.01.07
# Version : 1.1.2
# GitHub  : https://github.com/txubelaxu/esphome-jk-bms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# +--------------------------------------+
# | Component settings                   |
# +--------------------------------------+

jk_rs485_bms:
  - id: ${bms_name}_id
    rs485_address: ${bms_address}
    jk_rs485_sniffer_id: ${bms_sniffer_id}
    update_interval: ${bms_update_interval}

# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

switch:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: ${bms_name}_id
    precharging:
      name: ${name}_${bms_name}_precharging
    charging:
      name: ${name}_${bms_name}_charging
    discharging:
      name: ${name}_${bms_name}_discharging
    balancing:
      id: bms${bms_id}_switch_balancing
      name: ${name}_${bms_name}_balancing
    emergency:
      name: ${name}_${bms_name}_emergency
    heating:
      name: ${name}_${bms_name}_heating
    display_always_on:
      name: ${name} ${bms_name}_display_always_on
    charging_float_mode:
      name: ${name} ${bms_name}_charging_float_mode
    timed_stored_data:
      name: ${name}_${bms_name}_timed_stored_data
    disable_temperature_sensors:
      name: ${name}_${bms_name}_disable_temperature_sensors
    smart_sleep_on:
      name: ${name}_${bms_name}_smart_sleep_on
    disable_pcl_module:
      name: ${name}_${bms_name}_disable_pcl_module
    gps_heartbeat:
      name: ${name}_${bms_name}_gps_heartbeat
    port_selection:
      name: ${name}_${bms_name}_port_selection
    special_charger:
      name: ${name}_${bms_name}_special_charger

binary_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: ${bms_name}_id
    status_balancing:
      id: bms${bms_id}_equalizing
      name: ${name}_${bms_name}_status_balancing
    status_precharging:
      name: ${name}_${bms_name}_status_precharging
    status_charging:
      id: bms${bms_id}_charging_allowed
      name: ${name}_${bms_name}_status_charging
    status_discharging:
      id: bms${bms_id}_discharging_allowed
      name: ${name}_${bms_name}_status_discharging
    status_online:
      id: bms${bms_id}_online_status
      name: ${name}_${bms_name}_status_online
    status_heating:
      name: ${name}_${bms_name}_status_heating
    alarm_wireres:
      name: ${name}_${bms_name}_alarm_wireres
    alarm_mosotp:
      name: ${name}_${bms_name}_alarm_mosotp
    alarm_cellquantity:
      name: ${name}_${bms_name}_alarm_cellquantity
    alarm_cursensorerr:
      name: ${name}_${bms_name}_alarm_cursensorerr
    alarm_cellovp:
      name: ${name}_${bms_name}_alarm_cellovp
    alarm_batovp:
      name: ${name}_${bms_name}_alarm_batovp
    alarm_chocp:
      name: ${name}_${bms_name}_alarm_chocp
    alarm_chscp:
      name: ${name}_${bms_name}_alarm_chscp
    alarm_chotp:
      name: ${name}_${bms_name}_alarm_chotp
    alarm_chutp:
      name: ${name}_${bms_name}_alarm_chutp
    alarm_cpuauxcommuerr:
      name: ${name}_${bms_name}_alarm_cpuauxcommuerr
    alarm_celluvp:
      name: ${name}_${bms_name}_alarm_celluvp
    alarm_batuvp:
      name: ${name}_${bms_name}_alarm_batuvp
    alarm_dchocp:
      name: ${name}_${bms_name}_alarm_dchocp
    alarm_dchscp:
      name: ${name}_${bms_name}_alarm_dchscp
    alarm_dchotp:
      name: ${name}_${bms_name}_alarm_dchotp
    alarm_chargemos:
      name: ${name}_${bms_name}_alarm_chargemos
    alarm_dischargemos:
      name: ${name}_${bms_name}_alarm_dischargemos
    alarm_gpsdisconneted:
      name: ${name}_${bms_name}_alarm_gpsdisconnected
    alarm_modifypwdintime:
      name: ${name}_${bms_name}_alarm_modifypwdintime
    alarm_dischargeonfailed:
      name: ${name}_${bms_name}_alarm_dischargeonfailed
    alarm_batteryovertemp:
      name: ${name}_${bms_name}_alarm_batteryOvertemp
    alarm_temperaturesensoranomaly:
      name: ${name}_${bms_name}_alarm temperaturesensoranomaly
    alarm_plcmoduleanomaly:
      name: ${name}_${bms_name}_alarm_plcmoduleanomaly
    alarm_mostempsensorabsent:
      name: ${name}_${bms_name}_alarm_mostempsensorabsent
    alarm_battempsensor1absent:
      name: ${name}_${bms_name}_alarm_battempsensor1absent
    alarm_battempsensor2absent:
      name: ${name}_${bms_name}_alarm battempsensor2absent
    alarm_battempsensor3absent:
      name: ${name}_${bms_name}_alarm battempsensor3absent
    alarm_battempsensor4absent:
      name: ${name}_${bms_name}_alarm_battempsensor4absent
    alarm_battempsensor5absent:
      name: ${name}_${bms_name}_alarm_battempsensor5absent

sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: ${bms_name}_id
    balancing_direction:
      name: ${name}_${bms_name}_balancing_direction
    cell_voltage_min:
      id: bms${bms_id}_min_cell_voltage
      name: ${name}_${bms_name}_cell_voltage_min
    cell_voltage_max:
      id: bms${bms_id}_max_cell_voltage
      name: ${name}_${bms_name}_cell_voltage_max
    cell_voltage_min_cell_number:
      id: bms${bms_id}_min_voltage_cell
      name: ${name}_${bms_name}_cell_voltage_min_cell_number
    cell_voltage_max_cell_number:
      id: bms${bms_id}_max_voltage_cell
      name: ${name}_${bms_name}_cell_voltage_max_cell_number
    cell_delta_voltage:
      name: ${name}_${bms_name}_cell_delta_voltage
    cell_average_voltage:
      name: ${name}_${bms_name}_cell_average_voltage
    cell_resistance_min:
      name: ${name}_${bms_name}_cell_resistance_min
    cell_resistance_max:
      name: ${name}_${bms_name}_cell_resistance_max
    cell_resistance_min_cell_number:
      name: ${name}_${bms_name}_cell_resistance_min_cell_number
    cell_resistance_max_cell_number:
      name: ${name}_${bms_name}_cell_resistance_max_cell_number
    cell_voltage_01:
      name: ${name}_${bms_name}_cell_voltage_01
    cell_voltage_02:
      name: ${name}_${bms_name}_cell_voltage_02
    cell_voltage_03:
      name: ${name}_${bms_name}_cell_voltage_03
    cell_voltage_04:
      name: ${name}_${bms_name}_cell_voltage_04
    cell_voltage_05:
      name: ${name}_${bms_name}_cell_voltage_05
    cell_voltage_06:
      name: ${name}_${bms_name}_cell_voltage_06
    cell_voltage_07:
      name: ${name}_${bms_name}_cell_voltage_07
    cell_voltage_08:
      name: ${name}_${bms_name}_cell_voltage_08
    cell_voltage_09:
      name: ${name}_${bms_name}_cell_voltage_09
    cell_voltage_10:
      name: ${name}_${bms_name}_cell_voltage_10
    cell_voltage_11:
      name: ${name}_${bms_name}_cell_voltage_11
    cell_voltage_12:
      name: ${name}_${bms_name}_cell_voltage_12
    cell_voltage_13:
      name: ${name}_${bms_name}_cell_voltage_13
    cell_voltage_14:
      name: ${name}_${bms_name}_cell_voltage_14
    cell_voltage_15:
      name: ${name}_${bms_name}_cell_voltage_15
    cell_voltage_16:
      name: ${name}_${bms_name}_cell_voltage_16
    # cell_voltage_17:
    #   name: ${name}_${bms_name}_cell_voltage_17
    # cell_voltage_18:
    #   name: ${name}_${bms_name}_cell_voltage_18
    # cell_voltage_19:
    #   name: ${name}_${bms_name}_cell_voltage_19
    # cell_voltage_20:
    #   name: ${name}_${bms_name}_cell_voltage_20
    # cell_voltage_21:
    #   name: ${name}_${bms_name}_cell_voltage_21
    # cell_voltage_22:
    #   name: ${name}_${bms_name}_cell_voltage_22
    # cell_voltage_23:
    #   name: ${name}_${bms_name}_cell_voltage_23
    # cell_voltage_24:
    #   name: ${name}_${bms_name}_cell_voltage_24
    cell_resistance_01:
      name: ${name}_${bms_name}_cell_resistance_01
    cell_resistance_02:
      name: ${name}_${bms_name}_cell_resistance_02
    cell_resistance_03:
      name: ${name}_${bms_name}_cell_resistance_03
    cell_resistance_04:
      name: ${name}_${bms_name}_cell_resistance_04
    cell_resistance_05:
      name: ${name}_${bms_name}_cell_resistance_05
    cell_resistance_06:
      name: ${name}_${bms_name}_cell_resistance_06
    cell_resistance_07:
      name: ${name}_${bms_name}_cell_resistance_07
    cell_resistance_08:
      name: ${name}_${bms_name}_cell_resistance_08
    cell_resistance_09:
      name: ${name}_${bms_name}_cell_resistance_09
    cell_resistance_10:
      name: ${name}_${bms_name}_cell_resistance_10
    cell_resistance_11:
      name: ${name}_${bms_name}_cell_resistance_11
    cell_resistance_12:
      name: ${name}_${bms_name}_cell_resistance_12
    cell_resistance_13:
      name: ${name}_${bms_name}_cell_resistance_13
    cell_resistance_14:
      name: ${name}_${bms_name}_cell_resistance_14
    cell_resistance_15:
      name: ${name}_${bms_name}_cell_resistance_15
    cell_resistance_16:
      name: ${name}_${bms_name}_cell_resistance_16
    # cell_resistance_17:
    #   name: ${name}_${bms_name}_cell_resistance_17
    # cell_resistance_18:
    #   name: ${name}_${bms_name}_cell_resistance_18
    # cell_resistance_19:
    #   name: ${name}_${bms_name}_cell_resistance_19
    # cell_resistance_20:
    #   name: ${name}_${bms_name}_cell_resistance_20
    # cell_resistance_21:
    #   name: ${name}_${bms_name}_cell_resistance_21
    # cell_resistance_22:
    #   name: ${name}_${bms_name}_cell_resistance_22
    # cell_resistance_23:
    #   name: ${name}_${bms_name}_cell_resistance_23
    # cell_resistance_24:
    #   name: ${name}_${bms_name}_cell_resistance_24
    battery_voltage:
      id: bms${bms_id}_total_voltage
      name: ${name}_${bms_name}_battery_voltage
    battery_current:
      id: bms${bms_id}_current
      name: ${name}_${bms_name}_battery_current
    battery_power:
      id: bms${bms_id}_power
      name: ${name}_${bms_name}_battery_power
    battery_power_charging:
      id: bms${bms_id}_charging_power
      name: ${name}_${bms_name}_battery_power_charging
    battery_power_discharging:
      id: bms${bms_id}_discharging_power
      name: ${name}_${bms_name}_battery_power_discharging
    temperature_sensor_1:
      id: bms${bms_id}_temperature_sensor_1
      name: ${name}_${bms_name}_temperature_sensor_1
    temperature_sensor_2:
      id: bms${bms_id}_temperature_sensor_2
      name: ${name}_${bms_name}_temperature_sensor_2
    temperature_sensor_3:
      id: bms${bms_id}_temperature_sensor_3
      name: ${name}_${bms_name}_temperature_sensor_3
    temperature_sensor_4:
      id: bms${bms_id}_temperature_sensor_4
      name: ${name}_${bms_name}_temperature_sensor_4
    temperature_sensor_5:
      id: bms${bms_id}_temperature_sensor_5
      name: ${name}_${bms_name}_temperature_sensor_5
    temperature_powertube:
      name: ${name}_${bms_name}_temperature_powertube
    battery_capacity_state_of_charge:
      id: bms${bms_id}_soc
      name: ${name}_${bms_name}_battery_capacity_soc
    battery_capacity_remaining:
      id: bms${bms_id}_capacity_remaining_ah
      name: ${name}_${bms_name}_battery_capacity_remaining

    charging_cycles:
      id: bms${bms_id}_charging_cycles
      name: ${name}_${bms_name}_charging_cycles
    battery_capacity_total_charging_cycle:
      name: ${name}_${bms_name}_battery_capacity_total_charging_cycle
    battery_total_runtime:
      name: ${name}_${bms_name}_battery_total_runtime
    balancing_current:
      name: ${name}_${bms_name}_balancing_current
    errors_bitmask:
      id: bms${bms_id}_errors_bitmask
      name: ${name}_${bms_name}_errors_bitmask
    cell_count_real:
      name: ${name}_${bms_name}_cell_count_real

    smart_sleep_time:
      name: ${name}_${bms_name}_smart_sleep_time

    powertube_temperature_protection:
      name: ${name}_${bms_name}_powertube_temperature_protection
    powertube_temperature_protection_recovery:
      name: ${name}_${bms_name}_powertube_temperature_protection_recovery
    battery_total_alarms_count:     
      name: ${name}_${bms_name}_battery_total_alarms_count
    battery_total_alarms_active:     
      name: ${name}_${bms_name}_battery_total_alarms_active
    emergency_time_countdown:
      name: ${name}_${bms_name}_emergency_time_countdown
    uart1_protocol_number:
      name: ${name}_${bms_name}_uart1_protocol_number
    uart2_protocol_number:
      name: ${name}_${bms_name}_uart2_protocol_number
    battery_soh_valuation:    
      name: ${name}_${bms_name}_battery_soh_valuation
    discharging_overcurrent_protection_release_time:    
      name: ${name}_${bms_name}_discharging_overcurrent_protection_release_time
    discharging_short_circuit_protection_release_time:    
      name: ${name}_${bms_name}_discharging_short_circuit_protection_release_time
    charging_overcurrent_protection_release_time:    
      name: ${name}_${bms_name}_charging_overcurrent_protection_release_time
    charging_short_circuit_protection_release_time:    
      name: ${name}_${bms_name}_charging_short_circuit_protection_release_time
    cell_undervoltage_protection_release_time:    
      name: ${name}_${bms_name}_cell_undervoltage_protection_release_time
    cell_overvoltage_protection_release_time:    
      name: ${name}_${bms_name}_cell_overvoltage_protection_release_time

text_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: ${bms_name}_id
    errors:
      name: ${name}_${bms_name}_errors
    operation_status:
      name: ${name}_${bms_name}_operation_status
    battery_type:
      name: ${name}_${bms_name}_battery_type
    total_runtime_formatted:
      name: ${name}_${bms_name}_total_runtime_formatted
    info_vendorid:
      name: ${name}_${bms_name}_info_vendorid
    info_hardware_version:
      name: ${name}_${bms_name}_info_hardware_version
    info_software_version:
      name: ${name}_${bms_name}_info_software_version
    info_device_name:
      name: ${name}_${bms_name}_info_device_name
    info_device_password:
      name: ${name}_${bms_name}_info_device_password
    network_nodes_available:
      name: ${name}_${bms_name}_network_nodes_available
    info_device_serial_number:
      name: ${name}_${bms_name}_info_device_serial_number
    info_device_setup_passcode:
      name: ${name}_${bms_name}_info_device_setup_passcode         

number:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: ${bms_name}_id
    cell_smart_sleep_voltage:
      name: ${name}_${bms_name}_cell_smart_sleep_voltage
    cell_overvoltage_protection:
      id: bms${bms_id}_cell_ovp
      name: ${name}_${bms_name}_cell_overvoltage_protection
    cell_overvoltage_protection_recovery:
      id: bms${bms_id}_cell_ovpr
      name: ${name}_${bms_name}_cell_overvoltage_protection_recovery
    cell_request_charge_voltage:
      name: ${name}_${bms_name}_cell_request_charge_voltage
    cell_request_charge_voltage_time:
      name: ${name}_${bms_name}_cell_request_charge_voltage_time
    cell_request_float_voltage:
      name: ${name}_${bms_name}_cell_request_float_voltage
    cell_request_float_voltage_time:
      name: ${name}_${bms_name}_cell_request_float_voltage_time
    cell_balancing_trigger_voltage:
      id: bms${bms_id}_balance_trigger_voltage
      name: ${name}_${bms_name}_balancing_trigger_voltage
    cell_balancing_starting_voltage:
      name: ${name}_${bms_name}_cell_balancing_starting_voltage
    max_balancing_current:
      name: ${name}_${bms_name}_max_balancing_current
    cell_soc100_voltage:
      name: ${name}_${bms_name}_cell_soc100_voltage
    cell_soc0_voltage:
      name: ${name}_${bms_name}_cell_soc0_voltage
    cell_undervoltage_protection:
      id: bms${bms_id}_cell_uvp
      name: ${name}_${bms_name}_cell_undervoltage_protection
    cell_undervoltage_protection_recovery:
      id: bms${bms_id}_cell_uvpr
      name: ${name}_${bms_name}_cell_undervoltage_protection_recovery
    cell_power_off_voltage:
      name: ${name}_${bms_name}_cell_power_off_voltage
    cell_count_settings:
      id: bms${bms_id}_cell_count
      name: ${name}_${bms_name}_cell_count_settings    
    battery_capacity_total_settings:
      id: bms${bms_id}_battery_capacity
      name: ${name}_${bms_name}_battery_capacity_total_setting
    max_charging_current:
      id: bms${bms_id}_max_charge_current
      name: ${name}_${bms_name}_max_charging_current
    max_discharging_current:
      id: bms${bms_id}_max_discharge_current
      name: ${name}_${bms_name}_max_discharging_current
    charging_overcurrent_protection_delay:
      name: ${name}_${bms_name}_charging_overcurrent_protection_delay
    charging_overcurrent_protection_recovery_delay:
      name: ${name}_${bms_name}_charging_overcurrent_protection_recovery_delay
    discharging_overcurrent_protection_delay:
      name: ${name}_${bms_name}_discharging_overcurrent_protection_delay
    discharging_overcurrent_protection_recovery_delay:
      name: ${name}_${bms_name}_discharging_overcurrent_protection_recovery_delay
    short_circuit_protection_delay:
      name: ${name}_${bms_name}_short_circuit_protection_delay
    short_circuit_protection_recovery_delay:
      name: ${name}_${bms_name}_short_circuit_protection_recovery_delay
    precharging_time_from_discharge:
      name: ${name}_${bms_name}_precharging_time_from_discharge
    charging_overtemperature_protection:
      name: ${name}_${bms_name}_charging_overtemperature_protection
    charging_overtemperature_protection_recovery:
      name: ${name}_${bms_name}_charging_overtemperature_protection_recovery
    discharging_overtemperature_protection:
      name: ${name}_${bms_name}_discharging_overtemperature_protection
    discharging_overtemperature_protection_recovery:
      name: ${name}_${bms_name}_discharging_overtemperature_protection_recovery
    charging_lowtemperature_protection:
      name: ${name}_${bms_name}_charging_lowtemperature_protection
    charging_lowtemperature_protection_recovery:
      name: ${name}_${bms_name}_charging_lowtemperature_protection_recovery      
    mos_overtemperature_protection:
      name: ${name}_${bms_name}_mos_overtemperature_protection
    mos_overtemperature_protection_recovery:
      name: ${name}_${bms_name}_mos_overtemperature_protection_recovery
