external_components:
  - source: github://KinDR007/VictronMPPT-ESPHOME@main
    refresh: 0s

victron:
  - uart_id: ${inverter_uart_id}
    id: ${inverter_name}
    throttle: ${inverter_throttle}
  
sensor:
  - platform: victron
    victron_id: ${inverter_name}
    # update_interval: ${inverter_update_interval}
    charging_mode_id:
      name: ${name}_${inverter_name}_charging_mode_id
    error_code:
      name: ${name}_${inverter_name}_error_code
    ac_out_current:
      name: ${name}_${inverter_name}_ac_output_current
      id: ${inverter_name}_ac_output_current
    ac_out_voltage:
      name: ${name}_${inverter_name}_ac_out_voltage
      id: ${inverter_name}_ac_output_voltage
    yield_total:
      name: ${name}_${inverter_name}_yield_total
    yield_today:
      name: ${name}_${inverter_name}_yield_today
    max_power_today:
      name: ${name}_${inverter_name}_max_power_today
    yield_yesterday:
      name: ${name}_${inverter_name}_yield yesterday
    max_power_yesterday:
      name: ${name}_${inverter_name}_max_power_yesterday
    day_number:
      name: ${name}_${inverter_name}_day_number
    battery_current:
      name: ${name}_${inverter_name}_battery_current
    panel_power:
      name: ${name}_${inverter_name}_pv_power
      id: ${inverter_name}_pv_power
    battery_voltage:
      name: ${name}_${inverter_name}_battery_voltage
    panel_voltage:
      name: ${name}_${inverter_name}_pv_voltage
      id: ${inverter_name}_pv_voltage
    load_current:
      name: ${name}_${inverter_name}_load_current
    state_of_charge:
      name: ${name}_${inverter_name}_soc
    ac_out_apparent_power:
      name: ${name}_${inverter_name}_ac_output_apparent_power
    tracking_mode_id:
      name: ${name}_${inverter_name}_tracking_mode_id
   
  - platform: template
    name: ${name}_${inverter_name}_ac_output_active_power
    lambda: |-
       auto val = id(${inverter_name}_ac_output_voltage).state * id(${inverter_name}_ac_output_current).state;
       if (isnan(val))
          return {};
       return val;
    update_interval: ${inverter_template_update}
    
  - platform: template
    name: ${name}_${inverter_name}_pv_current
    lambda: |-
       auto val = id(${inverter_name}_pv_power).state / id(${inverter_name}_pv_voltage).state;
       if (isnan(val))
          return {};
       return val;
    update_interval: ${inverter_template_update}   

binary_sensor:
  - platform: victron
    victron_id: ${inverter_name}
    relay_state:
      name: ${name}_${inverter_name}_relay_state    
    
text_sensor:
  - platform: victron
    victron_id: ${inverter_name}
    # update_interval: ${inverter_text_update}
    alarm_reason:
      name: ${inverter_name}_alarm_reason   
    device_type:
      name: ${name}_${inverter_name}_device_type
    serial_number:
      name: ${name}_${inverter_name}_serial_number
    firmware_version_24bit:
      name: ${name}_${inverter_name}_firmware_version_24bit
    charging_mode:
      name: ${name}_${inverter_name}_charging_mode
    device_mode:
      name: ${name}_${inverter_name}_device mode

