modbus_controller:
 - id: ${pyranometer_name}_modbus_controller
   address: ${pyranometer_modbus_address}
   modbus_id: ${pyranometer_modbus_id}
   command_throttle: ${pyranometer_modbus_throttle}
   setup_priority: -10
   update_interval: ${pyranometer_update_interval}
   
   
sensor:

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: ${name}_${pyranometer_name}_solar_radiation
    id: ${pyranometer_name}_solar_radiation
    address: 0x0000
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0
    icon: mdi:sun-wireless
    skip_updates: 1
    unit_of_measurement: "W/m²"