# Updated : 2025.01.28
# Version : 1.1.3
# GitHub  : https://github.com/syssi/esphome-jdb-bms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  bms_base: !include bms_base.yaml
  bms_temperature_sensor: !include bms_temperature_sensor_6.yaml
  bms_errors_bitmask: !include bms_errors_bitmask_JBD.yaml

# +--------------------------------------+
# | Component settings                   |
# +--------------------------------------+

external_components:
  - source: github://syssi/esphome-jbd-bms@main
    refresh: 0s

uart:
  - id: !extend ${bms_uart_id}
    baud_rate: 9600

jbd_bms:
  - id: jbd_bms${bms_id}
    uart_id: ${bms_uart_id}
    update_interval: ${bms_update_interval}
    rx_timeout: ${bms_rx_timeout}

# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

button:
  - platform: jbd_bms
    jbd_bms_id: jbd_bms${bms_id}
    retrieve_hardware_version:
      name: "${name} ${bms_name} retrieve hardware version"

binary_sensor:
  - platform: jbd_bms
    jbd_bms_id: jbd_bms${bms_id}
    balancing:
      id: bms${bms_id}_equalizing
      name: "${name} ${bms_name} balancing"
    charging:
      id: bms${bms_id}_charging_allowed
      name: "${name} ${bms_name} charging"
    discharging:
      id: bms${bms_id}_discharging_allowed
      name: "${name} ${bms_name} discharging"
    online_status:
      id: bms${bms_id}_online_status
      name: "${name} ${bms_name} online status"

switch:
  - platform: jbd_bms
    jbd_bms_id: jbd_bms${bms_id}
    charging:
      id: bms${bms_id}_charge_switch
      name: "${name} ${bms_name} Charge switch"
    discharging:
      id: bms${bms_id}_discharge_switch
      name: "${name} ${bms_name} Discharge switch"

sensor:
  - platform: jbd_bms
    jbd_bms_id: jbd_bms${bms_id}
    battery_strings:
      name: "${name} ${bms_name} battery strings"
    current:
      id: bms${bms_id}_current
      name: "${name} ${bms_name} current"
    power:
      id: bms${bms_id}_power
      name: "${name} ${bms_name} power"
    charging_power:
      id: bms${bms_id}_charging_power
      name: "${name} ${bms_name} charging power"
    discharging_power:
      id: bms${bms_id}_discharging_power
      name: "${name} ${bms_name} discharging power"
    state_of_charge:
      id: bms${bms_id}_state_of_charge
      name: "${name} ${bms_name} state of charge"
    nominal_capacity:
      id: bms${bms_id}_battery_capacity
      name: "${name} ${bms_name} nominal capacity"
    charging_cycles:
      id: bms${bms_id}_charging_cycles
      name: "${name} ${bms_name} charging cycles"
    capacity_remaining:
      id: bms${bms_id}_capacity_remaining_ah
      name: "${name} ${bms_name} capacity remaining"
    battery_cycle_capacity:
      name: "${name} ${bms_name} battery cycle capacity"
    total_voltage:
      id: bms${bms_id}_total_voltage
      name: "${name} ${bms_name} total voltage"
    average_cell_voltage:
      id: bms${bms_id}_average_cell_voltage
      name: "${name} ${bms_name} average cell voltage"
    delta_cell_voltage:
      name: "${name} ${bms_name} delta cell voltage"
    min_cell_voltage:
      id: bms${bms_id}_min_cell_voltage
      name: "${name} ${bms_name} min cell voltage"
    max_cell_voltage:
      id: bms${bms_id}_max_cell_voltage
      name: "${name} ${bms_name} max cell voltage"
    min_voltage_cell:
      id: bms${bms_id}_min_voltage_cell
      name: "${name} ${bms_name} min voltage cell"
    max_voltage_cell:
      id: bms${bms_id}_max_voltage_cell
      name: "${name} ${bms_name} max voltage cell"
    temperature_1:
      id: bms${bms_id}_temperature_sensor_1
      name: "${name} ${bms_name} temperature 1"
    temperature_2:
      id: bms${bms_id}_temperature_sensor_2
      name: "${name} ${bms_name} temperature 2"
    temperature_3:
      id: bms${bms_id}_temperature_sensor_3
      name: "${name} ${bms_name} temperature 3"
    temperature_4:
      id: bms${bms_id}_temperature_sensor_4
      name: "${name} ${bms_name} temperature 4"
    temperature_5:
      id: bms${bms_id}_temperature_sensor_5
      name: "${name} ${bms_name} temperature 5"
    temperature_6:
      id: bms${bms_id}_temperature_sensor_6
      name: "${name} ${bms_name} temperature 6"
    cell_voltage_1:
      name: "${name} ${bms_name} cell voltage 01"
    cell_voltage_2:
      name: "${name} ${bms_name} cell voltage 02"
    cell_voltage_3:
      name: "${name} ${bms_name} cell voltage 03"
    cell_voltage_4:
      name: "${name} ${bms_name} cell voltage 04"
    cell_voltage_5:
      name: "${name} ${bms_name} cell voltage 05"
    cell_voltage_6:
      name: "${name} ${bms_name} cell voltage 06"
    cell_voltage_7:
      name: "${name} ${bms_name} cell voltage 07"
    cell_voltage_8:
      name: "${name} ${bms_name} cell voltage 08"
    cell_voltage_9:
      name: "${name} ${bms_name} cell voltage 09"
    cell_voltage_10:
      name: "${name} ${bms_name} cell voltage 10"
    cell_voltage_11:
      name: "${name} ${bms_name} cell voltage 11"
    cell_voltage_12:
      name: "${name} ${bms_name} cell voltage 12"
    cell_voltage_13:
      name: "${name} ${bms_name} cell voltage 13"
    cell_voltage_14:
      name: "${name} ${bms_name} cell voltage 14"
    cell_voltage_15:
      name: "${name} ${bms_name} cell voltage 15"
    cell_voltage_16:
      name: "${name} ${bms_name} cell voltage 16"
    # cell_voltage_17:
    #   name: "${name} ${bms_name} cell voltage 17"
    # cell_voltage_18:
    #   name: "${name} ${bms_name} cell voltage 18"
    # cell_voltage_19:
    #   name: "${name} ${bms_name} cell voltage 19"
    # cell_voltage_20:
    #   name: "${name} ${bms_name} cell voltage 20"
    # cell_voltage_21:
    #   name: "${name} ${bms_name} cell voltage 21"
    # cell_voltage_22:
    #   name: "${name} ${bms_name} cell voltage 22"
    # cell_voltage_23:
    #   name: "${name} ${bms_name} cell voltage 23"
    # cell_voltage_24:
    #   name: "${name} ${bms_name} cell voltage 24"
    # cell_voltage_25:
    #   name: "${name} ${bms_name} cell voltage 25"
    # cell_voltage_26:
    #   name: "${name} ${bms_name} cell voltage 26"
    # cell_voltage_27:
    #   name: "${name} ${bms_name} cell voltage 27"
    # cell_voltage_28:
    #   name: "${name} ${bms_name} cell voltage 28"
    # cell_voltage_29:
    #   name: "${name} ${bms_name} cell voltage 29"
    # cell_voltage_30:
    #   name: "${name} ${bms_name} cell voltage 30"
    # cell_voltage_31:
    #   name: "${name} ${bms_name} cell voltage 31"
    # cell_voltage_32:
    #   name: "${name} ${bms_name} cell voltage 32"
    operation_status_bitmask:
      name: "${name} ${bms_name} operation status bitmask"
    errors_bitmask:
      id: bms${bms_id}_errors_bitmask
      name: "${name} ${bms_name} errors bitmask"
    balancer_status_bitmask:
      name: "${name} ${bms_name} balancer status bitmask"
    software_version:
      name: "${name} ${bms_name} software version"

  # Required sensors cannot be retrieved from BMS
  # max_charge_current
  - platform: template
    id: bms${bms_id}_max_charge_current
    name: "${name} ${bms_name} max charge current"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: A
    icon: mdi:current-dc
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_max_charge_current};
  # max_discharge_current
  - platform: template
    id: bms${bms_id}_max_discharge_current
    name: "${name} ${bms_name} max discharge current"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: A
    icon: mdi:current-dc
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_max_discharge_current};
  # cell_ovp
  - platform: template
    id: bms${bms_id}_cell_ovp
    name: "${name} ${bms_name} cell ovp"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: V
    device_class: voltage
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: return ${bms_cell_ovp};
  # cell_uvp
  - platform: template
    id: bms${bms_id}_cell_uvp
    name: "${name} ${bms_name} cell uvp"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: V
    device_class: voltage
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: return ${bms_cell_uvp};
  # balance_trigger_voltage
  - platform: template
    id: bms${bms_id}_balance_trigger_voltage
    name: "${name} ${bms_name} balance trigger voltage"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: V
    device_class: voltage
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: return ${bms_balance_trigger_voltage};

text_sensor:
  - platform: jbd_bms
    jbd_bms_id: jbd_bms${bms_id}
    errors:
      name: "${name} ${bms_name} errors"
    operation_status:
      name: "${name} ${bms_name} operation status"
    device_model:
      name: "${name} ${bms_name} device model"
