globals:  
  - id: ${residual_solar_production_name}_energy_yesterday_global
    type: float
    restore_value: yes


time:
  - platform: homeassistant #sntp
    id: !extend my_time
    on_time:
      - seconds: 59
        minutes: 59
        hours: 23
        then:           
          - globals.set:
              id: ${residual_solar_production_name}_energy_yesterday_global
              value: !lambda return ( id(${residual_solar_production_name}_energy_yesterday_global) =  float( id(${residual_solar_production_name}_energy_today).state) );


sensor:
  - platform: template
    name: ${name}_${residual_solar_production_name}_power
    id: ${residual_solar_production_name}_power
    accuracy_decimals: 1
    icon: mdi:power
    unit_of_measurement: 'W'
    update_interval: ${residual_solar_production_template_update}
    lambda: |-
      float power = 0.0f; 
      if (float(id($residual_solar_production_battery_charging_power).state)>=0.0){
        power = (float(id($residual_solar_production_pyranometer_power).state)) -(float(id($residual_solar_production_load_power).state) + float(id($residual_solar_production_battery_charging_power).state)); 
       }
      return power;
      
  - platform: total_daily_energy
    name: ${name}_${residual_solar_production_name}_energy_today
    id: ${residual_solar_production_name}_energy_today
    power_id: ${residual_solar_production_name}_power
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    method: trapezoid
    filters:
       # Multiplication factor from W to kW is 0.001
       - multiply: 0.001
    icon: mdi:counter
  
  - platform: template
    name: ${name}_${residual_solar_production_name}_energy_yesterday
    id: ${residual_solar_production_name}_energy_yesterday
    unit_of_measurement: 'kWh'
    accuracy_decimals: 1
    icon: mdi:power
    update_interval: ${residual_solar_production_template_update}
    lambda: |-
      return ( id(${residual_solar_production_name}_energy_yesterday).state = id(${residual_solar_production_name}_energy_yesterday_global) );
    