# Updated : 2025.06.16
# Version : 1.1.1
# GitHub  : https://github.com/SeByDocKy/pvbrain2

substitutions:
  board_chip: "ESP32-S3"
  board_name: "PVbrain2"

packages:
  board_base: !include board_base.yaml
  board_base_wifi: !include board_base_wifi.yaml
  board_rgb_led: !include board_options_rgb_led_status.yaml

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB # ajust according to your ESP32-S3 version
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing
    board_upload.maximum_ram_size: 524288 # total Size of the internal RAM in bits, it's the same for all ESP32-S3

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # domain: !secret domain

logger:
  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"
  hardware_uart: UART0 # UART0 / USB_SERIAL_JTAG

light:
  # https://esphome.io/components/light/esp32_rmt_led_strip
  # ESP Light used to see the inverter heartbeat
  # Internal : only specifying an id without a name will implicitly set this to true.
  - platform: esp32_rmt_led_strip
    id: esp_light
    # name: ${name} ESP32 Light
    rgb_order: GRB
    pin: 38
    num_leds: 1
    # rmt_channel: 0
    chipset: ws2812
    entity_category: config
    default_transition_length: 0ms
