# external_components:
#   - source:
#       type: git
#       url: https://github.com/ssieb/custom_components
#     components: [ growatt ]
#     refresh: 0s
    
external_components:
  - source: github://SeByDocKy/myESPhome/
    components: [growatt]
    refresh: 0s    
    
sensor:
  - platform: growatt
    id: ${inverter_name}_id
    address: ${inverter_modbus_address}
    modbus_id: ${inverter_modbus_id}
    input_power:
      name: ${name}_${inverter_name}_input_power
      id: ${inverter_name}_input_power
    pv1_voltage:
      name: ${name}_${inverter_name}_pv1_voltage
      id: ${inverter_name}_pv1_voltage
    pv1_current:
      name: ${name}_${inverter_name}_pv1_current
      id: ${inverter_name}_pv1_current
    pv1_power:
      name: ${name}_${inverter_name}_pv1_power
      id: ${inverter_name}_pv1_power
    pv2_voltage:
      name: ${name}_${inverter_name}_pv2_voltage
      id: ${inverter_name}_pv2_voltage
    pv2_current:
      name: ${name}_${inverter_name}_pv2_current
      id: ${inverter_name}_pv2_current
    pv2_power:
      name: ${name}_${inverter_name}_pv2_power
      id: ${inverter_name}_pv2_power
    output_power:
      name: ${name}_${inverter_name}_output_power 
      id: ${inverter_name}_output_power 
    grid_frequency:
      name: ${name}_${inverter_name}_grid_frequency
      id: ${inverter_name}_grid_frequency
    ac_voltage:
      name: ${name}_${inverter_name}_ac_voltage
      id: ${inverter_name}_ac_voltage
    ac_current:
      name: ${name}_${inverter_name}_ac_current
      id: ${inverter_name}_ac_current
    ac_power:
      name: ${name}_${inverter_name}_ac_power
      id: ${inverter_name}_ac_power
    today_gen:
      name: ${name}_${inverter_name}_pv_energy_generated_today
      id: ${inverter_name}_pv_energy_generated_today
      icon: mdi:counter
    total_gen:
      name: ${name}_${inverter_name}_pv_energy_generated_total
      id: ${inverter_name}_pv_energy_generated_total
      icon: mdi:counter
    temperature:
      name: ${name}_${inverter_name}_temperature
      id: ${inverter_name}_temperature
    today_grid:
      name: ${name}_${inverter_name}_grid_energy_imported_today
      id: ${inverter_name}_grid_energy_imported_today
      icon: mdi:counter
    total_grid:
      name: ${name}_${inverter_name}_grid_energy_imported_total
      id: ${inverter_name}_grid_energy_imported_total
      icon: mdi:counter      