external_components:
  - source: github://KinDR007/VictronMPPT-ESPHOME@main
    refresh: 0s

victron:
  - uart_id: ${solar_charger_uart_id}
    id: ${solar_charger_name}
    throttle: ${solar_charger_throttle}
    
sensor:
  - platform: victron
    victron_id: ${solar_charger_name}
    # update_interval: ${solar_charger_update_interval}
    charging_mode_id:
      name: ${name}_${solar_charger_name}_charging_mode_id
    error_code:
      name: ${name}_${solar_charger_name}_error_code
    ac_out_current:
      name: ${name}_${solar_charger_name}_ac_output_current
      id: ${solar_charger_name}_ac_output_current
    ac_out_voltage:
      name: ${name}_${solar_charger_name}_ac_out_voltage
      id: ${solar_charger_name}_ac_output_voltage
    yield_total:
      name: ${name}_${solar_charger_name}_yield_total
      device_class: 'power'
      unit_of_measurement: 'kWh'
      filters:
        - multiply:  0.001
    yield_today:
      name: ${name}_${solar_charger_name}_yield_today
      device_class: 'power'
      unit_of_measurement: 'kWh'
      filters:
        - multiply:  0.001
    max_power_today:
      name: ${name}_${solar_charger_name}_max_power_today
    yield_yesterday:
      name: ${name}_${solar_charger_name}_yield yesterday
      device_class: 'power'
      unit_of_measurement: 'kWh'
      filters:
        - multiply:  0.001
    max_power_yesterday:
      name: ${name}_${solar_charger_name}_max_power_yesterday
    day_number:
      name: ${name}_${solar_charger_name}_day_number
    battery_current:
      name: ${name}_${solar_charger_name}_battery_current
    panel_power:
      name: ${name}_${solar_charger_name}_pv_power
      id: ${solar_charger_name}_pv_power
    battery_voltage:
      name: ${name}_${solar_charger_name}_battery_voltage
    panel_voltage:
      name: ${name}_${solar_charger_name}_pv_voltage
      id: ${solar_charger_name}_pv_voltage
    load_current:
      name: ${name}_${solar_charger_name}_load_current
    state_of_charge:
      name: ${name}_${solar_charger_name}_soc
    ac_out_apparent_power:
      name: ${name}_${solar_charger_name}_ac_output_apparent_power
    tracking_mode_id:
      name: ${name}_${solar_charger_name}_tracking_mode_id
      
  - platform: template
    name: ${name}_${solar_charger_name}_ac_output_active_power
    icon: mdi:power
    device_class: 'power'
    unit_of_measurement: 'W'
    accuracy_decimals: 1    
    lambda: |-
       auto val = id(${solar_charger_name}_ac_output_voltage).state * id(${solar_charger_name}_ac_output_current).state;
       if (isnan(val))
          return {};
       return val;
    update_interval: ${solar_charger_template_update}
    
  - platform: template
    name: ${name}_${solar_charger_name}_pv_current
    icon: mdi:current-dc
    device_class: 'current'
    unit_of_measurement: 'A'
    accuracy_decimals: 1    
    lambda: |-
       auto val = id(${solar_charger_name}_pv_power).state / id(${solar_charger_name}_pv_voltage).state;
       if (isnan(val))
          return {};
       return val;
    update_interval: ${solar_charger_template_update}

text_sensor:
  - platform: victron
    victron_id: ${solar_charger_name}
    # update_interval: ${solar_charger_text_update}
    alarm_reason:
      name: ${solar_charger_name}_alarm_reason
    device_type:
      name: ${name}_${solar_charger_name}_device_type
    serial_number:
      name: ${name}_${solar_charger_name}_serial_number
    firmware_version_24bit:
      name: ${name}_${solar_charger_name}_firmware_version_24bit
    charging_mode:
      name: ${name}_${solar_charger_name}_charging_mode
    error:
      name: ${name}_${solar_charger_name}_error
    device_mode:
      name: ${name}_${solar_charger_name}_device mode

    
