# Updated : 2024.07.29
# Version : 1.0.3
# GitHub  : https://github.com/Dackara/

# +--------------------------------------+
# | Example of use                       |
# +--------------------------------------+
# | DEBUG ( logger level must be DEBUG ) |
# +--------------------------------------+

  # device_debug: !include
  #   file: pvbrain2/base/device_debug.yaml
  #   vars:
  #     debug_name: 'Debug'
  #     debug_update_interval: '5s'
  #     # Size of your PSRAM in bits
  #     # 8Mb='8388608' | 6Mb='6291456' | 4Mb='4194304' | 2Mb='2097152' | NoPSRAM='0'
  #     debug_psram_size: '8388608'

# +--------------------------------------+

# The PSRAM platform must be included for the sensor of the same name to work
# The psram: platform is already declared in the main YAML 'pvbrain2.yam'
# psram:

debug:
  update_interval: ${debug_update_interval}

text_sensor:
  - platform: debug
    device:
      name: ${name}_${debug_name}_device_info
      id: ${debug_name}_device_info
    reset_reason:
      name: ${name}_${debug_name}_reset_reason
      id: ${debug_name}_reset_reason

sensor:
  - platform: debug
    free:
      name: ${name}_${debug_name}_heap_free
      id: ${debug_name}_heap_free
    block:
      name: ${name}_${debug_name}_heap_max_block
      id: ${debug_name}_heap_max_block
    psram:
      name: ${name}_${debug_name}_free_PSRAM
      id: ${debug_name}_free_psram
    loop_time:
      name: ${name}_${debug_name}_loop_time
      id: ${debug_name}_loop_time

  - platform: template
    name: ${name}_${debug_name}_heap_free_percent
    id: ${debug_name}_heap_free_percent
    unit_of_measurement: '%'
    accuracy_decimals: 2
    icon: mdi:percent
    update_interval: ${debug_update_interval}
    entity_category: diagnostic
    # 524288 B (SRAM total)
    # 327680 B (DRAM usable)
    lambda: return ( id(${debug_name}_heap_free).state * 100 / 327680 );

  - platform: template
    name: ${name}_${debug_name}_heap_max_block_percent
    id: ${debug_name}_heap_max_block_percent
    unit_of_measurement: '%'
    accuracy_decimals: 2
    icon: mdi:percent
    update_interval: ${debug_update_interval}
    entity_category: diagnostic
    # 524288 B (SRAM total)
    # 327680 B (DRAM usable)
    lambda: return ( id(${debug_name}_heap_max_block).state * 100 / 327680 );

  - platform: template
    name: ${name}_${debug_name}_free_psram_percent
    id: ${debug_name}_free_psram_percent
    unit_of_measurement: '%'
    accuracy_decimals: 2
    icon: mdi:percent
    update_interval: ${debug_update_interval}
    entity_category: diagnostic
    lambda: return ( id(${debug_name}_free_psram).state * 100 / ${debug_psram_size} ); // 8388608
