modbus_controller:
  - id: ${powermeter_name}_modbus_controller
    address: ${powermeter_modbus_address}
    modbus_id: ${powermeter_modbus_id}
    command_throttle: ${powermeter_modbus_throttle}
    setup_priority: -10
    update_interval: ${powermeter_update_interval}
   
sensor:

  - platform: modbus_controller
    modbus_controller_id: ${powermeter_name}_modbus_controller
    name: ${name}_${powermeter_name}_phase_a_voltage
    id: ${powermeter_name}_phase_a_voltage
    register_type: holding
    address: 0x0100
    unit_of_measurement: 'V'
    device_class: voltage
    state_class: measurement
    value_type: U_WORD
    accuracy_decimals: 1
    icon: mdi:sine-wave
    filters:
      - multiply: 0.01     # value = DATA / 100

  - platform: modbus_controller
    modbus_controller_id: ${powermeter_name}_modbus_controller
    name: ${name}_${powermeter_name}_phase_b_voltage
    id: ${powermeter_name}_phase_b_voltage
    register_type: holding
    address: 0x0101
    unit_of_measurement: 'V'
    device_class: voltage
    state_class: measurement
    value_type: U_WORD
    accuracy_decimals: 1
    icon: mdi:sine-wave
    filters:
      - multiply: 0.01     # value = DATA / 100

  - platform: modbus_controller
    modbus_controller_id: ${powermeter_name}_modbus_controller
    name: ${name}_${powermeter_name}_phase_c_voltage
    id: ${powermeter_name}_phase_c_voltage
    register_type: holding
    address: 0x0102
    unit_of_measurement: 'V'
    device_class: voltage
    state_class: measurement
    value_type: U_WORD
    accuracy_decimals: 1
    icon: mdi:sine-wave
    filters:
      - multiply: 0.01     # value = DATA / 100   
